import 'package:flutter/material.dart';

class AppTheme {
  static ThemeData theme(ColorScheme colorScheme) => ThemeData(
        useMaterial3: true,
        brightness: colorScheme.brightness,
        colorScheme: colorScheme,
        scaffoldBackgroundColor: colorScheme.surface,
        canvasColor: colorScheme.surface,
      );

  static ColorScheme lightScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff546524),
      surfaceTint: Color(0xff546524),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xffd7eb9b),
      onPrimaryContainer: Color(0xff161e00),
      secondary: Color(0xff5b6146),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xffe0e6c4),
      onSecondaryContainer: Color(0xff181e09),
      tertiary: Color(0xff3a665e),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xffbcece2),
      onTertiaryContainer: Color(0xff00201c),
      error: Color(0xffba1a1a),
      onError: Color(0xffffffff),
      errorContainer: Color(0xffffdad6),
      onErrorContainer: Color(0xff410002),
      surface: Color(0xfffbfaed),
      onSurface: Color(0xff1b1c15),
      onSurfaceVariant: Color(0xff46483c),
      outline: Color(0xff76786b),
      outlineVariant: Color(0xffc6c8b8),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff303129),
      inversePrimary: Color(0xffbbcf81),
      primaryFixed: Color(0xffd7eb9b),
      onPrimaryFixed: Color(0xff161e00),
      primaryFixedDim: Color(0xffbbcf81),
      onPrimaryFixedVariant: Color(0xff3d4c0d),
      secondaryFixed: Color(0xffe0e6c4),
      onSecondaryFixed: Color(0xff181e09),
      secondaryFixedDim: Color(0xffc3caa9),
      onSecondaryFixedVariant: Color(0xff434930),
      tertiaryFixed: Color(0xffbcece2),
      onTertiaryFixed: Color(0xff00201c),
      tertiaryFixedDim: Color(0xffa1d0c6),
      onTertiaryFixedVariant: Color(0xff204e47),
      surfaceDim: Color(0xffdbdbcf),
      surfaceBright: Color(0xfffbfaed),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfff5f4e8),
      surfaceContainer: Color(0xffefeee2),
      surfaceContainerHigh: Color(0xffe9e9dd),
      surfaceContainerHighest: Color(0xffe3e3d7),
    );
  }

  ThemeData light() {
    return theme(lightScheme());
  }

  static ColorScheme lightMediumContrastScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff394808),
      surfaceTint: Color(0xff546524),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xff6a7b38),
      onPrimaryContainer: Color(0xffffffff),
      secondary: Color(0xff3f452d),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xff71775b),
      onSecondaryContainer: Color(0xffffffff),
      tertiary: Color(0xff1c4a43),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xff507d74),
      onTertiaryContainer: Color(0xffffffff),
      error: Color(0xff8c0009),
      onError: Color(0xffffffff),
      errorContainer: Color(0xffda342e),
      onErrorContainer: Color(0xffffffff),
      surface: Color(0xfffbfaed),
      onSurface: Color(0xff1b1c15),
      onSurfaceVariant: Color(0xff424438),
      outline: Color(0xff5e6053),
      outlineVariant: Color(0xff7a7c6e),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff303129),
      inversePrimary: Color(0xffbbcf81),
      primaryFixed: Color(0xff6a7b38),
      onPrimaryFixed: Color(0xffffffff),
      primaryFixedDim: Color(0xff526221),
      onPrimaryFixedVariant: Color(0xffffffff),
      secondaryFixed: Color(0xff71775b),
      onSecondaryFixed: Color(0xffffffff),
      secondaryFixedDim: Color(0xff595f44),
      onSecondaryFixedVariant: Color(0xffffffff),
      tertiaryFixed: Color(0xff507d74),
      onTertiaryFixed: Color(0xffffffff),
      tertiaryFixedDim: Color(0xff37645c),
      onTertiaryFixedVariant: Color(0xffffffff),
      surfaceDim: Color(0xffdbdbcf),
      surfaceBright: Color(0xfffbfaed),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfff5f4e8),
      surfaceContainer: Color(0xffefeee2),
      surfaceContainerHigh: Color(0xffe9e9dd),
      surfaceContainerHighest: Color(0xffe3e3d7),
    );
  }

  ThemeData lightMediumContrast() {
    return theme(lightMediumContrastScheme());
  }

  static ColorScheme lightHighContrastScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff1c2600),
      surfaceTint: Color(0xff546524),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xff394808),
      onPrimaryContainer: Color(0xffffffff),
      secondary: Color(0xff1f240f),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xff3f452d),
      onSecondaryContainer: Color(0xffffffff),
      tertiary: Color(0xff002822),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xff1c4a43),
      onTertiaryContainer: Color(0xffffffff),
      error: Color(0xff4e0002),
      onError: Color(0xffffffff),
      errorContainer: Color(0xff8c0009),
      onErrorContainer: Color(0xffffffff),
      surface: Color(0xfffbfaed),
      onSurface: Color(0xff000000),
      onSurfaceVariant: Color(0xff23251b),
      outline: Color(0xff424438),
      outlineVariant: Color(0xff424438),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff303129),
      inversePrimary: Color(0xffe1f5a3),
      primaryFixed: Color(0xff394808),
      onPrimaryFixed: Color(0xffffffff),
      primaryFixedDim: Color(0xff253100),
      onPrimaryFixedVariant: Color(0xffffffff),
      secondaryFixed: Color(0xff3f452d),
      onSecondaryFixed: Color(0xffffffff),
      secondaryFixedDim: Color(0xff292f18),
      onSecondaryFixedVariant: Color(0xffffffff),
      tertiaryFixed: Color(0xff1c4a43),
      onTertiaryFixed: Color(0xffffffff),
      tertiaryFixedDim: Color(0xff00332d),
      onTertiaryFixedVariant: Color(0xffffffff),
      surfaceDim: Color(0xffdbdbcf),
      surfaceBright: Color(0xfffbfaed),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfff5f4e8),
      surfaceContainer: Color(0xffefeee2),
      surfaceContainerHigh: Color(0xffe9e9dd),
      surfaceContainerHighest: Color(0xffe3e3d7),
    );
  }

  ThemeData lightHighContrast() {
    return theme(lightHighContrastScheme());
  }

  static ColorScheme darkScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xffbbcf81),
      surfaceTint: Color(0xffbbcf81),
      onPrimary: Color(0xff283500),
      primaryContainer: Color(0xff3d4c0d),
      onPrimaryContainer: Color(0xffd7eb9b),
      secondary: Color(0xffc3caa9),
      onSecondary: Color(0xff2d331c),
      secondaryContainer: Color(0xff434930),
      onSecondaryContainer: Color(0xffe0e6c4),
      tertiary: Color(0xffa1d0c6),
      onTertiary: Color(0xff033730),
      tertiaryContainer: Color(0xff204e47),
      onTertiaryContainer: Color(0xffbcece2),
      error: Color(0xffffb4ab),
      onError: Color(0xff690005),
      errorContainer: Color(0xff93000a),
      onErrorContainer: Color(0xffffdad6),
      surface: Color(0xff13140d),
      onSurface: Color(0xffe3e3d7),
      onSurfaceVariant: Color(0xffc6c8b8),
      outline: Color(0xff909284),
      outlineVariant: Color(0xff46483c),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffe3e3d7),
      inversePrimary: Color(0xff546524),
      primaryFixed: Color(0xffd7eb9b),
      onPrimaryFixed: Color(0xff161e00),
      primaryFixedDim: Color(0xffbbcf81),
      onPrimaryFixedVariant: Color(0xff3d4c0d),
      secondaryFixed: Color(0xffe0e6c4),
      onSecondaryFixed: Color(0xff181e09),
      secondaryFixedDim: Color(0xffc3caa9),
      onSecondaryFixedVariant: Color(0xff434930),
      tertiaryFixed: Color(0xffbcece2),
      onTertiaryFixed: Color(0xff00201c),
      tertiaryFixedDim: Color(0xffa1d0c6),
      onTertiaryFixedVariant: Color(0xff204e47),
      surfaceDim: Color(0xff13140d),
      surfaceBright: Color(0xff393a32),
      surfaceContainerLowest: Color(0xff0d0f08),
      surfaceContainerLow: Color(0xff1b1c15),
      surfaceContainer: Color(0xff1f2019),
      surfaceContainerHigh: Color(0xff292b23),
      surfaceContainerHighest: Color(0xff34352d),
    );
  }

  ThemeData dark() {
    return theme(darkScheme());
  }

  static ColorScheme darkMediumContrastScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xffc0d385),
      surfaceTint: Color(0xffbbcf81),
      onPrimary: Color(0xff121900),
      primaryContainer: Color(0xff869851),
      onPrimaryContainer: Color(0xff000000),
      secondary: Color(0xffc8cead),
      onSecondary: Color(0xff131805),
      secondaryContainer: Color(0xff8d9476),
      onSecondaryContainer: Color(0xff000000),
      tertiary: Color(0xffa5d4ca),
      onTertiary: Color(0xff001a16),
      tertiaryContainer: Color(0xff6c9990),
      onTertiaryContainer: Color(0xff000000),
      error: Color(0xffffbab1),
      onError: Color(0xff370001),
      errorContainer: Color(0xffff5449),
      onErrorContainer: Color(0xff000000),
      surface: Color(0xff13140d),
      onSurface: Color(0xfffcfbef),
      onSurfaceVariant: Color(0xffcbccbc),
      outline: Color(0xffa3a495),
      outlineVariant: Color(0xff828476),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffe3e3d7),
      inversePrimary: Color(0xff3e4d0e),
      primaryFixed: Color(0xffd7eb9b),
      onPrimaryFixed: Color(0xff0d1300),
      primaryFixedDim: Color(0xffbbcf81),
      onPrimaryFixedVariant: Color(0xff2d3b00),
      secondaryFixed: Color(0xffe0e6c4),
      onSecondaryFixed: Color(0xff0e1302),
      secondaryFixedDim: Color(0xffc3caa9),
      onSecondaryFixedVariant: Color(0xff333921),
      tertiaryFixed: Color(0xffbcece2),
      onTertiaryFixed: Color(0xff001511),
      tertiaryFixedDim: Color(0xffa1d0c6),
      onTertiaryFixedVariant: Color(0xff0b3d36),
      surfaceDim: Color(0xff13140d),
      surfaceBright: Color(0xff393a32),
      surfaceContainerLowest: Color(0xff0d0f08),
      surfaceContainerLow: Color(0xff1b1c15),
      surfaceContainer: Color(0xff1f2019),
      surfaceContainerHigh: Color(0xff292b23),
      surfaceContainerHighest: Color(0xff34352d),
    );
  }

  ThemeData darkMediumContrast() {
    return theme(darkMediumContrastScheme());
  }

  static ColorScheme darkHighContrastScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xfff7ffd6),
      surfaceTint: Color(0xffbbcf81),
      onPrimary: Color(0xff000000),
      primaryContainer: Color(0xffc0d385),
      onPrimaryContainer: Color(0xff000000),
      secondary: Color(0xfff8fedb),
      onSecondary: Color(0xff000000),
      secondaryContainer: Color(0xffc8cead),
      onSecondaryContainer: Color(0xff000000),
      tertiary: Color(0xffebfff9),
      onTertiary: Color(0xff000000),
      tertiaryContainer: Color(0xffa5d4ca),
      onTertiaryContainer: Color(0xff000000),
      error: Color(0xfffff9f9),
      onError: Color(0xff000000),
      errorContainer: Color(0xffffbab1),
      onErrorContainer: Color(0xff000000),
      surface: Color(0xff13140d),
      onSurface: Color(0xffffffff),
      onSurfaceVariant: Color(0xfffbfceb),
      outline: Color(0xffcbccbc),
      outlineVariant: Color(0xffcbccbc),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffe3e3d7),
      inversePrimary: Color(0xff232e00),
      primaryFixed: Color(0xffdcef9f),
      onPrimaryFixed: Color(0xff000000),
      primaryFixedDim: Color(0xffc0d385),
      onPrimaryFixedVariant: Color(0xff121900),
      secondaryFixed: Color(0xffe4eac8),
      onSecondaryFixed: Color(0xff000000),
      secondaryFixedDim: Color(0xffc8cead),
      onSecondaryFixedVariant: Color(0xff131805),
      tertiaryFixed: Color(0xffc1f1e6),
      onTertiaryFixed: Color(0xff000000),
      tertiaryFixedDim: Color(0xffa5d4ca),
      onTertiaryFixedVariant: Color(0xff001a16),
      surfaceDim: Color(0xff13140d),
      surfaceBright: Color(0xff393a32),
      surfaceContainerLowest: Color(0xff0d0f08),
      surfaceContainerLow: Color(0xff1b1c15),
      surfaceContainer: Color(0xff1f2019),
      surfaceContainerHigh: Color(0xff292b23),
      surfaceContainerHighest: Color(0xff34352d),
    );
  }

  ThemeData darkHighContrast() {
    return theme(darkHighContrastScheme());
  }
}
